### ISSUE TITLE
DownZemAll Crashes, may be due to Qt5Core.dll version issue MSVC x64

### ISSUE THREAD

**Issue by Ferretaa** [setvisible/DownZemAll#10]
When attempting to use the wizard with MSVC x64 version DZA just closes. 
Reading TROUBLESHOOTING.md  indicates: "Replace the faulty Qt5Core.dll (built on 03/11/2019) with the same version as the one of the other DLLs. " 
Question where do I find an alternative version? in particular the recommended version: 
Qt5Core.dll built on 02/11/2019 

It seems that the  TROUBLESHOOTING.md  is missing some key information to resolve this issue.
Install file used: DownZemAll_v2.0.3_windows-msvc-x64.zip

**Comment by setvisible** [comment]
It's a bug in DZA.

I think QtWebEngineProcess.exe is missing in this archive.

Copying QtWebEngineProcess.exe to the app's directory doesn't fix the issue unfortunately. 

Actually Qt5Core.dll contains a hard-coded path inside :

    qt_prfxpath=C:\Qt\5.13.2\msvc2017_64 

It seems this hard-coded path is used by the Qt5 WebEngine to find the QtWebEngineProcess.exe, and also mandatory dlls, resources, translations... The Qt documentation says the path could be overriden by an optional "qt.conf". Maybe this is the solution.

https://doc.qt.io/qt-5/qt-conf.html

To be investigated...

**Comment by setvisible** [comment]
Fixed in [v2.0.8](https://github.com/setvisible/DownZemAll/releases/tag/v2.0.8)
