### ISSUE TITLE
YouTube Playlists

### ISSUE THREAD

**Issue by LukeZBaker** [setvisible/DownZemAll#12]
Are there any plans to support playlists such as:

https://www.youtube.com/playlist?list=PLoROMvodv4rOSOPzutgyCTapiGlY2Nd8u

**Comment by setvisible** [comment]
There is work to be done, but I must admit that this feature would be very useful.

(From my perspective, the feature could come quickly if the covid20 quarantine happens)

**Comment by setvisible** [comment]
Merge v2.0.5
