### ISSUE TITLE
DownZemAll AppImage does not run

### ISSUE THREAD

**Issue by probonopd** [setvisible/DownZemAll#13]
DownZemAll AppImage does not run on Ubuntu xenial:

```
Fatal: This application failed to start because it could not find or load the Qt platform plugin "xcb".
```

Reference:
https://github.com/AppImage/appimage.github.io/pull/2192

**Comment by nicolaasjan** [comment]
Same here in Linux Mint 19.3...

**Comment by setvisible** [comment]
Duplicate of #78
