### ISSUE TITLE
[Fedora KDE] DownZemAll doesn't quit when right clicking tray icon and selecting "Quit"

### ISSUE THREAD

**Issue by pizzadude** [setvisible/DownZemAll#14]
Hi, thanks for this program. I have been looking for a replacement for the old DownThemAll extension. Seems to work fine in Fedora KDE with Brave Browser. I had to manually edit the json file to get it to work though. 

One issue I noticed is that DownZemAll doesn't quit when right clicking tray icon and selecting "Quit", or when pressing Ctrl + Q. The process stays running. Currently I have to manually kill the program when I want to quit it.

Other than that, the program works well. Thanks!

**Comment by pizzadude** [comment]
For the the manifest.json, I had to change the name of the file to "com.setvisible.downrightnow.json", and set the path to where I put DownZemAll inside the json. The json goes into "~/.config/BraveSoftware/Brave-Browser/NativeMessagingHosts/".

For the bug, it happens all the time. For the process to exit I have to kill the program from the terminal.

**Comment by LinuxCuba** [comment]
Confirm in KDENeon this bug it happens all the time. For the process to exit I have to kill the program from the terminal.
and ubuntu 18.04/20.04, the program not close. 
I'm updated the version to 2.0.6, and problem persist.
Other issue is the extension is not install in firefox 80.0.1 the last version. And not update.

**Comment by LinuxCuba** [comment]
Confirm in KDENeon this bug it happens all the time. For the process to exit I have to kill the program from the terminal.
And ubuntu 18.04/20.04, the program not close. 
I'm updated the version to 2.0.6, and problem persist.
Other issue is the extension is not install in firefox 80.0.1 the last version. And not update. 
This problem is because the extension is no signed. Mozilla demands all extension signed actually.  Please sign this. 
![2020-09-07_17-14](https://user-images.githubusercontent.com/25325199/92416903-a3abf780-f12d-11ea-9c6d-0c51b77444d7.png)

**Comment by setvisible** [comment]
Hi,
I installed a virtual machine with KDE Neon, and I could reproduce the bug.
So I'm currently investigating the issue and tell you if some progress.
Regards

**Comment by setvisible** [comment]
The issue is the System Tray icon (notification area). For some reason it goes wrong with KDE.

*Workaround:*

Go to **Options** > **Preferences** > **Interface** 
Disable "**Show system tray icon**"

The application should close correctly.

**Comment by pizzadude** [comment]
Confirmed fixed in latest version.

**Comment by LinuxCuba** [comment]
> The issue is the System Tray icon (notification area). For some reason it goes wrong with KDE.
> 
> _Workaround:_
> 
> Go to **Options** > **Preferences** > **Interface**
> Disable "**Show system tray icon**"
> 
> The application should close correctly.

yes, is closed, but, not show anymore the system tray icon, this not correct behavior.

**Comment by LinuxCuba** [comment]
Add option to keep in the system tray when closing, not only when minimizing, if you want it not to close and keep running. Close window, do not close the program.
