### ISSUE TITLE
Chromium extension installation error in Vivaldi (win64bit)

### ISSUE THREAD

**Issue by Uwe-B** [setvisible/DownZemAll#16]
While trying to install the actual Chromium extension (2.0.7) in Vivaldi browser (3.4.2066.94 (Stable channel) (64-Bit)), I get the following error:

Packet not valid. Details: "Variable $START$ used but not defined."

**Comment by setvisible** [comment]
Hi,

I tried the add-on on Vivaldi (same version as you) but couldn't reproduce the bug. My first thought is that it could be an issue with a translation file maybe. Could you change the browser language to 'english' (default language) and retry? 

However a variable called '$START$ doesn't seem related to this project. It looks more like a javascript (or powershell?) variable...

Maybe reinstall the add-on (some files are maybe corrupted)

Sorry for not helping that much.

**Comment by Uwe-B** [comment]
Thanks for the support!
You were right, changing the Language in Vivaldi to English (US) solved the issue. Down Right Now is now successfully installed.
