### ISSUE TITLE
Working in Linux ?

### ISSUE THREAD

**Issue by arnauldb** [setvisible/DownZemAll#2]
Hello,

How to make in work in Linux? I downloaded the 64 version and installed the addon but the addon can't find the launcher.

Thank you.

**Comment by rizaumami** [comment]
I don't think it will.
Well, until they create a Linux installer script .
Until v1.7.4 script included inside the tarball is Windows batch script.
I think the script is to connecting DownZemAll to Firefox's native messaging host.

**Comment by setvisible** [comment]
Correct. The script for Linux / MacOs isn't implemented yet.

**Comment by JTruj1ll0923** [comment]
This does work with the native client plugin, however.

**Comment by arnauldb** [comment]
> This does work with the native client plugin, however.

What do you mean? Can you get it work in Linux with the addon?
Thks.

**Comment by JTruj1ll0923** [comment]
Yep :) I will attach screenshots.
![Shows the name in the toolbar](https://user-images.githubusercontent.com/6656643/79825752-2d158580-8357-11ea-9ae5-4a85530d24f7.png)
![Opening page](https://user-images.githubusercontent.com/6656643/79825754-2e46b280-8357-11ea-9b18-f9dd395306c2.png)
![Downloaded files](https://user-images.githubusercontent.com/6656643/79825755-2edf4900-8357-11ea-8559-e891f9cf7c81.png)

**Comment by setvisible** [comment]
If you give the URL of a HTML page to DownZemAll , it parses the HTML (with Gumbo or Chromium) to find the <a> links. (no need of a web browser). I think that's what happened here.

(what remains untested is the connection between Firefox/Chrome/.. and DownZemAll through the web-extension's native-messaging on Linux and MacOs)

**Comment by JTruj1ll0923** [comment]
If that is what the native client plugin you mention [here](https://github.com/setvisible/DownZemAll/blob/develop/NativeClient.md), then sure. But I did not just give DownZemAll the html page. I clicked the button within Firefox.

**Comment by LinuxCuba** [comment]
It is impossible to achieve the integration in linux, I am using kdeneon, the latest version of firefox. There is no installation and integration script as if it exists for windows. The plugins in the browser are unable to detect DownZemAll running. Please build a .deb, snap, flatpak or appimages, but it works.

:~/install-DownZemAll-cmake$ ./DownZemAlld 
 | +  void WorkerThread::setEnabled(bool) false
 | +  void WorkerThread::setEnabled(bool) false
 | +  virtual void WorkerThread::run()
Couldn't open file.
 | +  void WorkerThread::setEnabled(bool) true
void StreamUpgrader::runAsync() "[pid:29745]  ./youtube-dl --update"
void StreamUpgrader::onStarted()
"youtube-dl is up-to-date (2020.05.08)"
 | +  void WorkerThread::setEnabled(bool) true
void StreamUpgrader::runAsync() "[pid:29781]  ./youtube-dl --update"
void StreamUpgrader::onStarted()
"youtube-dl is up-to-date (2020.05.08)"
void StreamUpgrader::runAsync() "[pid:29789]  ./youtube-dl --update"
void StreamUpgrader::onStarted()
"youtube-dl is up-to-date (2020.05.08)"
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 10122, resource id: 29704941, major code: 40 (TranslateCoords), minor code: 0
^C
![2020-05-19_23-17_1](https://user-images.githubusercontent.com/25325199/82401194-2433d480-9a27-11ea-88a3-bae2c09d989f.png)

![2020-05-19_23-17](https://user-images.githubusercontent.com/25325199/82401234-40d00c80-9a27-11ea-88e8-372879de16ea.png)

![2020-05-19_23-27](https://user-images.githubusercontent.com/25325199/82401809-cb653b80-9a28-11ea-99d7-dfb5478fcd9b.png)

**Comment by setvisible** [comment]
This issue is now fixed in v2.0.2

(successfully tested on Ubuntu 20.04 LTS with Firefox 76)

Run "install.sh" to install the native messaging host
(and "uninstall.sh" to remove it)

**Comment by LinuxCuba** [comment]
Thank you, very much. Please make a linux package, as .deb, rpm, snap, flatpak o appimages. 
Signer the firefox complement. firma-de-complementos-en-firefox?as=u&utm_source=inproduct
![2020-05-24_17-02](https://user-images.githubusercontent.com/25325199/82764936-a84bda80-9de0-11ea-94f3-92c8d5923777.png)
And in the install_shortcut_desktop.sh insert after 12 
chmod +x $TARGET

Other problem is determinate the language in the system. In my laptop Desktop is in Spanish (Escritorio) and the script failed.

The program could not be found
![2020-05-24_17-23](https://user-images.githubusercontent.com/25325199/82765287-6c664480-9de3-11ea-91eb-40090b1a49ae.png)
 «/home/linuxcuba/DownZemAll_v2.0.2_x86_64-linux-gnu/desktop_shortcut/DownZemAll»
This is not a good method for determinate the path to exec. 
REPLACE_escaped=$(echo $REPLACE | sed 's_/_\\/_g')
BY_escaped=$(echo $BY | sed 's_/_\\/_g')

sed -i 's/'"$REPLACE_escaped"'/'"$BY_escaped"'/g' $TARGET

Because install_shortcut_desktop.sh is not calling from install.sh. and $PWD is not correct.

![2020-05-24_17-46](https://user-images.githubusercontent.com/25325199/82765648-98cf9000-9de6-11ea-9899-8745abe23ddd.png)

Best regards.

**Comment by arnauldb** [comment]
Thank you for your work.

**Comment by setvisible** [comment]
Thank you for your valuable input !

I just commited your fix:
https://github.com/setvisible/DownZemAll/commit/323ea4e79f952dd46bd42e3cf575434312ef9f83

**Comment by setvisible** [comment]
@LinuxCuba : I'm currently doing the internationalization of the app, and was wondering if you'd like to have a Spanish translation? Regarding the screenshots you've made and the degree of interest you proved by fixing this issue, I thought you would be the perfect person to translate it. If you want of course. It's better if it's translate by someone who actually uses it. 

The UI uses currently 600 words, and will probably stay as this for a while, given that the software is quite stable now...

I have set up Transifex to simplify the process : 
https://www.transifex.com/downzemall/downzemall/

Let me know if you're interested ! :)

**Comment by LinuxCuba** [comment]
> @LinuxCuba : I'm currently doing the internationalization of the app, and was wondering if you'd like to have a Spanish translation? Regarding the screenshots you've made and the degree of interest you proved by fixing this issue, I thought you would be the perfect person to translate it. If you want of course. It's better if it's translated by someone who actually uses it.
> 
> The UI uses currently 600 words, and will probably stay as is for a while, given that the software is quite stable now...
> 
> I have set up Transifex to simplify the process of translation :
> https://www.transifex.com/downzemall/downzemall/
> 
> Let me know if you're interested ! :)

Yes, I am interested and collaborate in the internationalization of the project, I would really like to be able to collaborate with it, and thus contribute my grain of sand, such as collaborating and beta tester. You can write to me privately if you wish, so we can coordinate better. Thank you.

**Comment by LinuxCuba** [comment]
I have already made the request to join the project in Transifex. ;)
