### ISSUE TITLE
Change number of download active

### ISSUE THREAD

**Issue by gabri25ele** [setvisible/DownZemAll#20]
I don't find option to change the contemporaries download.
in preferences I find only torrent.global.active.
Where is it?

**Comment by setvisible** [comment]
Hello,
What are "contemporaries downloads"? 
Cheers

**Comment by gabri25ele** [comment]
> What are "contemporaries downloads"?


sorry, error in translation.
"simultaneous downloads" is the right definition (or active downloads)?

**Comment by setvisible** [comment]
If you want to change the number of concurrent downloads (number of files downloaded in parallel), go to **Option** > **Preference** > **Network** and change "**concurrent downloads**". It's 4 by default. 

For a torrent it's different (a Torrent can generally contain several files in it). By default, the files are **downloaded randomly**, but you can change the priority of each of them with **right-click on the file(s)** > **Priority: ...** You can also _ignore_ some files, which saves bandwidth and avoids downloading unwanted parts. 

Hope it helps :)
