### ISSUE TITLE
Feature request and question

### ISSUE THREAD

**Issue by nero-0** [setvisible/DownZemAll#21]
Hi!
Firstly I'd like to say thank you for maintaining this awesome project. So thank you! :)

Secondly, I'd like to know if it is possible to provide a portable version of DZA. By that I mean a version that stores the settings and such in the root folder where DZA is. What do you think?

Finally, I'd like to contribute with the translation to pt-BR. It is not available on the transifex page, nor can I request it (for some reason I don't know). So, could you add it?

Edit: Forgot to ask, is there any plan to add a dark theme/mode as an option? I'd love to see that on DZA! (Literally, hurts the eyes less :joy_cat:)

That's it, thanks for reading!

Kind regards

**Comment by setvisible** [comment]
Hi,
Thanks for your thanks! :)

**Portable version with local config file**: Sure it's possible to add the feature. 

**pt_BR translation**: Thanks for your contribution ! I just added the .ts/.json files to the project. It's on the `develop` branch. Let me know when you think it's mature enough for release.

**Dark theme**: it's probably feasable, with a dedicated sheetstyle in Qt maybe. Let's open a ticket for it! Maybe some specialists in UI could contribute or give some help. Indeed the current icons might look horrible with a dark background.

Good luck for translating :)

Cheers,

**Comment by setvisible** [comment]
FYI, the option added to Preferences (develop branch):

- pt_BR and pt_PT both appear.

![language](https://user-images.githubusercontent.com/20563751/102011298-85185680-3d43-11eb-8dc1-2f3c3b95dd84.png)

**Comment by nero-0** [comment]
Thanks for the quick response!

> Thanks for your contribution ! I just added the .ts/.json files to the project. It's on the develop branch.

I requested to join the pt-BR team, I'm on the pt-PT team atm. Could you remove me or move to pt-BR, if possible?
I'm "nexro" there (transifex).

> Let me know when you think it's mature enough for release.

For sure. 😄 

> Portable version with local config file: Sure it's possible to add the feature.

In addition to that, if you don't have it in mind, can you add an option to change the location of the ".cache" folder? To actually make things more portable.

**Comment by setvisible** [comment]
Transifex done.

The .cache folder is part of Youtube-DL default config, but hopefully there's an option to define it. It should be quite easy to add this option in DZA.

**Comment by nero-0** [comment]
Pretty nice, thanks for the tip!

**Comment by nero-0** [comment]
> Let me know when you think it's mature enough for release.
Done.
Some changes can be made over time if necessary, such as when I have more affinity with DZA! for example. 😸

**Comment by nero-0** [comment]
> Let me know when you think it's mature enough for release.

Done.
Some changes can be made over time if necessary, such as when I have more affinity with DZA! for example. 😸

**Comment by nero-0** [comment]
> Let me know when you think it's mature enough for release.

Done.
Some changes can be made over time if necessary, such as when I have more affinity with DZA! for example. 😸
But for now it's pretty decent from my point of view.

**Comment by setvisible** [comment]
Wow, you did an amazing job! So quickly moreover. (I didn't expected that coming so fast :))

I will commit your changes today.

I want to mention your work in the Release Note. Are you ok if I reference your github nikename "nero-0" as contributor for pt_BR ?

On transifex, there's also the Web-Extension, with about 50 chunks of text. Could you translate them as well?

Thanks for your contribution anyway!

**Comment by nero-0** [comment]
> Wow, you did an amazing job! So quickly moreover. (I didn't expected that coming so fast :))

Yes, the tool you suggested made things a lot easier.
It's much more intuitive when you can see things directly in the GUI.

> Are you ok if I reference your github nikename "nero-0" as contributor for pt_BR ?

Sure, as you prefer.

> On transifex, there's also the Web-Extension, with about 50 chunks of text. Could you translate them as well?

Yes, it's done.

> Thanks for your contribution anyway!

No problem, it was fun. 😄 


Hope you have a good day!
