### ISSUE TITLE
mp4upload.com

### ISSUE THREAD

**Issue by candrapersada** [setvisible/DownZemAll#26]
why download videos don't work with mp4upload.com?

**Comment by setvisible** [comment]
The site isn't supported by youtube-dl yet:
https://github.com/ytdl-org/youtube-dl/pull/16958

Perhaps follow the ticket and wait for their merge. Once done, it should be ready in DZA when Y-DL publishes the new release. Indeed DZA runs automatic Y-DL upgrade.

I'll close this ticket.
