### ISSUE TITLE
Filename does not support Chinese

### ISSUE THREAD

**Issue by oopo0** [setvisible/DownZemAll#29]
![gGB1ErLWoH](https://user-images.githubusercontent.com/67009994/107444418-7f899200-6b75-11eb-8eaf-0afa9f9fee64.png)

**Comment by setvisible** [comment]
Yeah the last release (v2.2.2) introduced this bug. Should not be long to fix...

However if you want the fix now, just downgrade to **version 2.2.1**. 

https://github.com/setvisible/DownZemAll/releases/tag/v2.2.1

Regards

**Comment by oopo0** [comment]
Great, thank you very much!
