### ISSUE TITLE
Transiflex - Add Italian language item (empty)

### ISSUE THREAD

**Issue by bovirus** [setvisible/DownZemAll#31]
@setvisible 

Could you please create in Transiflex page

https://www.transifex.com/downzemall/downzemall/

the item for Italian lnaguage.

Then I can ask you to joint to the team for Italian language.

Then I can help also to improve NSIS installer script for Window to have a multilanguage installer.

Thanks.

**Comment by setvisible** [comment]
Buongiorno Bovirus,

Grazie mille for your contribution!

I just added the TX and JSON files :
https://www.transifex.com/downzemall/downzemall/language/it_IT/

Btw, everything is in branch "feature-translation-italian", but what you have to do is just translate / review with transifex. Once you're done, tell me, I'll push the code and release.

FYI Google Chrome doesn't like my web-extension, They accuse it to download Youtube ! So they try to pressure youtube-dl users like DZA, and block any new release deployment... We are stuck with v2.2.0 in Chrome, until they go back to Earth and change their policy.

For NSIS, I wrote the script such a long time ago, I have no idea how it works anymore. If you do so, please create a dedicated branch, once it's good for you, tell me too, I'll rebase and merge.

Ciao :)
