### ISSUE TITLE
DownZemAll 2.2.3 - Translation issues

### ISSUE THREAD

**Issue by bovirus** [setvisible/DownZemAll#34]
@setvisible 

Please check screenshots about translatiuon issues.
The item in red boxes are untranslated strings.

![DownZemAll-2 2 3-01](https://user-images.githubusercontent.com/1262554/112472555-92df6e00-8d6d-11eb-9d64-4d40db99887e.jpg)

![DownZemAll-2 2 3-02](https://user-images.githubusercontent.com/1262554/112472558-93780480-8d6d-11eb-8e31-c6092031d3e8.jpg)

![DownZemAll-2 2 3-03](https://user-images.githubusercontent.com/1262554/112472560-94109b00-8d6d-11eb-93e5-8a840a16e78d.jpg)

![DownZemAll-2 2 3-04](https://user-images.githubusercontent.com/1262554/112472563-94109b00-8d6d-11eb-9499-84092141189a.jpg)

![DownZemAll-2 2 3-05](https://user-images.githubusercontent.com/1262554/112472565-94109b00-8d6d-11eb-8be6-a0ce8982904d.jpg)

![DownZemAll-2 2 3-06](https://user-images.githubusercontent.com/1262554/112472567-94a93180-8d6d-11eb-82b8-e4b9996af20a.jpg)

![DownZemAll-2 2 3-07](https://user-images.githubusercontent.com/1262554/112472568-94a93180-8d6d-11eb-9700-88ee532ef0e2.jpg)

**Comment by setvisible** [comment]
Fixed.
Could you please translate the 7 new italian sentences in transifex?
Then, we can release it.
Cheers,

**Comment by bovirus** [comment]
@setvisible 

7 strings added to Italian language.

What's about "License text" inA bout window?
will it remain iNE nglish?

Thanks.

**Comment by setvisible** [comment]
For the licence, well it's a lot of work for a text that generally nobody reads...

**Comment by bovirus** [comment]
OK. Thanks.
