### ISSUE TITLE
DownZemAll 2.3.0 - String issue in the installer

### ISSUE THREAD

**Issue by bovirus** [setvisible/DownZemAll#37]
@setvisible 

Hello.

Thanks for new version 2.3.0.

Pelase check screenshot about issue with installer

![image](https://user-images.githubusercontent.com/1262554/112714967-7b26f780-8edd-11eb-8e45-97076e456a67.png)

Couild be also modify NSIS script to create an exe file that contain version info

**Now**

DownZemAll_x86_Setup.exe
DownZemAll_x86_Setup.exe

**Proposal**

DownZemAll_2.3.0_x86.exe
DownZemAll_2.3.0_x64.exe

**Comment by setvisible** [comment]
Bad ${DESC_VisitWebSite} fixed.
