### ISSUE TITLE
NSIS installer - New component dialog layout

### ISSUE THREAD

**Issue by bovirus** [setvisible/DownZemAll#39]
@setvisible 

In NSIS there is an option to use the new component layout that offer more space for string description.

Example of another sofwtare that use NSIS installer and new component dialog layout.
 
![image](https://user-images.githubusercontent.com/1262554/113412971-ee3add00-93b9-11eb-8b11-83bd0cda1916.png)

Please check if you can please use it.

**Comment by setvisible** [comment]
Done
