### ISSUE TITLE
Paste list of URLs to start downloads

### ISSUE THREAD

**Issue by marioawad** [setvisible/DownZemAll#40]
First thank you for this amazing downloader.

I remember there used to be a way to download by pasting a list of URLs but can no longer find it. Can you please help? 

If not available, can you please look into implementing it as it is faster than saving list of URLs to file and then using the Import From File option from the menu.

Thanks again.

**Comment by setvisible** [comment]
Available in v2.3.2

Explained here:
https://setvisible.github.io/DownZemAll/urls/2021/04/30/list-of-urls.html

Have a nice weekend
;)
