### ISSUE TITLE
yt-dlp support

### ISSUE THREAD

**Issue by smaragdus** [setvisible/DownZemAll#44]
Since [youtube-dl](https://github.com/ytdl-org/youtube-dl) may be [abandoned](https://github.com/ytdl-org/youtube-dl/issues/29965) (latest version - [2021.06.06](https://github.com/ytdl-org/youtube-dl/releases/tag/2021.06.06)), support for [yt-dlp](https://github.com/yt-dlp/yt-dlp) may be considered in the future since this fork seems to be actively developed (latest version - [2021.10.10](https://github.com/yt-dlp/yt-dlp/releases/tag/2021.10.10)).

**Comment by setvisible** [comment]
\<troll>Some say the two maintainers both died from COVID.\</troll>

It looks like Sergey M is busy (house moving):
https://github.com/ytdl-org/youtube-dl/issues/30022#issuecomment-931772923

Maybe the issue will be magically solved in a few weeks.

Let's keep an eye on it!

**Comment by smaragdus** [comment]
@setvisible 

I really hope that [youtube-dl](https://github.com/ytdl-org/youtube-dl) is not dead, that the developer will come back to it and a new release will be published. If this does not happen [yt-dlp](https://github.com/yt-dlp/yt-dlp) is the obvious fork to replace [youtube-dl](https://github.com/ytdl-org/youtube-dl).

Perhaps another solution might be that [DownZemAll!](https://setvisible.github.io/DownZemAll/) supports both [youtube-dl](https://github.com/ytdl-org/youtube-dl) and [yt-dlp](https://github.com/yt-dlp/yt-dlp) and the user is able to choose which engine to use for downloading of videos.

If it happens that [youtube-dl](https://github.com/ytdl-org/youtube-dl) stops working with the most video sites I thought of a manual workaround:

- delete **youtube-dl.exe**;
- rename **yt-dlp.exe** to **youtube-dl.exe**;
- replace the deleted executable with the renamed executable;

I suppose that this might work but I haven't tried it yet.

**Comment by setvisible** [comment]
Tried to rename yt-dl.exe in youtube-dl.exe... It works!

The fix should be quick to implement.

**Comment by setvisible** [comment]
Fixed in v2.5.0
