### ISSUE TITLE
About windows untranslated

### ISSUE THREAD

**Issue by bovirus** [setvisible/DownZemAll#51]
@setvisible 

Is it normal that "About" window for DownZemAll and QT are un untranslated?

![image](https://user-images.githubusercontent.com/1262554/140726659-82037f68-e336-4934-8f80-0f0966d0e305.png)

![image](https://user-images.githubusercontent.com/1262554/140726703-6128fd4f-160d-44c5-814a-38b7a151724b.png)

Could be possible to add relkative strings in language file?

**Comment by setvisible** [comment]
Hi
Indeed there was a whoopsie in `about.h`.
Will be fixed in the next release.
Thanks

**Comment by setvisible** [comment]
Guess it's fixed now
