### ISSUE TITLE
Do I really need to install DownZemAll?

### ISSUE THREAD

**Issue by tyeeman** [setvisible/DownZemAll#6]
I downloaded the zip package and see there is an install.bat file. I do not intend to use DownRightNow with my browser, so I don't think I need to run the installer do I?

**Comment by setvisible** [comment]
_install.bat_ is only useful if you use the addon DownRightNow : it adds the registry keys to let the addon know where is _downzemal.exe_.

PS : install.bat can be undo with uninstall.bat.
