### ISSUE TITLE
Some issues and Ideas to make it the best

### ISSUE THREAD

**Issue by mx202** [setvisible/DownZemAll#7]
Hello,

I would like to tell you that the DownZemAll program is a wonderful program and I think it should me worked on to make it really usable

And I would like to give you some notes, some problems, and ways to develop the program if you allow me to, please

1 / Make a video download box appear above videos like IDM
2 / Make the video download box disappear after pressing Download or Exit the page
3 / I strongly recommend that you modify the design of the user interface to be more modern and attractive to encourage the use of the program and compete with the wonderful user interface designs of IDM and Flareget
4/ build DownZemAll as Flatpak and Snap for linux users

That's what I would recommend and I'm sure that DownZemAll will be the best download manager in the near future

Thank you a lot 

Best regard

**Comment by setvisible** [comment]
Thanks for your feedback. It's interesting to read a detailed post like this one.

Just a couple of questions to clarify:

1/ & 2/ Is it a thumbnail of the video? Maybe adding it to the selection dialogbox (when clicking File > Download Stream...), and also to the details information dialog box, when clicking on a video item in the queue > right-click > Information (or Alt-I) would be the good thing?

3/ It's a good idea. DZA was originally based on the UI of legacy DTA (DownThemAll). No effort was invested in that direction until now :)

4/ I implemented an AppImage build recently. Is it sufficient? The main issue with package builds (against a simple Tarball) is that DZA is actually not 1 but 3 executables. Operationally, your web browser calls the launcher, that calls DownZemAll, that then calls youtubedl. (in the future it could call other executable like ffmpeg). I don't see any solution to make it a single package. The solution could be to split it in 2 package builds, however the advantage of an unique package (as you observe) is lost.

Btw I appreciate all the points you mention.

Currently I'm struggling with the *torrent engine* which is a real brainteaser, so don't be surprised if your interesting suggestions take some time to be implemented :)

**NB:** If you are a non-english native speaker, would you like to translate this app in your native language? If you want to contribute, see [Transifex project page](https://www.transifex.com/downzemall/downzemall/) and the [README](https://github.com/setvisible/DownZemAll/blob/develop/TRANSLATORS.md). If you can't, it's ok, just asking:)

Regards

**Comment by mx202** [comment]
Hello again

One of my online business is testing applications for some companies
Therefore, I find myself somewhat familiar with what is effective and necessary to make the program spread widely

An answer to your first question / still I think the user does not want to look at and enter the settings menu, but it should be easy to use the program, and all settings should be easy and set by default.
So I prefer to use the option (the above video dialog box) because this is easier, faster and away from the settings entry menu

Regarding point 2 you mentioned / I hope that you will look at this project at this link
https://github.com/salemebo/Ariafx
The user interface is attractive and very stimulating to use the program
It is really attractive and attracts us to use it

3 / The program format `Appimage` iis generally good and I do not have much information about it but the program did not work when I converted it to an executable file and did not work when I tried to run it via the Terminal and show me this message

```
This application failed to start because it could not find or load the Qt platform plugin "xcb".

Reinstalling the application may fix this problem.
Aborted

```
Regarding the idea of ​​calling `ffmpeg`, this is a very nice idea and very very useful

4 / Regarding the torrent engine / although it is a nice idea but I do not recommend this thing currently because there are excellent programs that do this and adding this feature will not help in spreading the program at the moment
I prefer to keep your effort to develop the mechanism of downloading and capturing files from the browser as well as the user interface and when you achieve an advanced achievement in all these matters you can add some secondary features such as torrent engine

5 / About translation: I am an Arab boy and I will do so in support of you even though I work in English all the time.

In the end, I am not here to judge what is best and what is not, but I like you and your program and want to see it spreads and controls its class.

**Comment by mx202** [comment]
It intentionally crossed many points because it could be implemented later
And I didn't want to make the subject any longer

thank you very much

**Comment by andrew-phi** [comment]
Please consider making the usual .deb | rpm packages - this would help a LOT. Because, for example, I want to install and update DZA for all users. I'd love to see DZA included in ubuntu )
PS: I missed a good dl manager for so long! Thank you!

**Comment by setvisible** [comment]
This application failed to start because it could not find or load the Qt platform plugin "xcb".

Maybe duplicate with https://github.com/setvisible/DownZemAll/issues/78
