### ISSUE TITLE
DownZemAll_v2.0.3_x86_64.tar.gz

### ISSUE THREAD

**Issue by LukeZBaker** [setvisible/DownZemAll#8]
When extracting DownZemAll_v2.0.3_x86_64.tar.gz, files are dumped to the current directory, rather than the normal process of creating a separate directory, like with DownZemAll-2.0.3.tar.gz.

**Comment by setvisible** [comment]
Hi
It's something to see with tar, 7z etc maybe. The target directory is defined by the zip tool maybe.
Cheers
