### ISSUE TITLE
Where are the devs ? Is this project already dead ?!

### ISSUE THREAD

**Issue by jarredou** [setvisible/DownZemAll#84]
Seeing there is no more support from the dev since weeks/months, is this project already dead ?

**Comment by setvisible** [comment]
Hi there,

As long as people uses it, and as long as the software runs, it's alive. It's a free project, free to use and modify. It gathers free contributions. In other words, people could implement a feature or fork the project, as they wish. 

Support is eventually possible, but understand that it's a self-service mode.

If you want to spend time to develop a new feature or fix a bug, feel free to do so.

Regards,
