### ISSUE TITLE
AppImage for 2.0.3

### ISSUE THREAD

**Issue by LukeZBaker** [setvisible/DownZemAll#9]
Running the AppImage file generates the error:

```
Fatal: This application failed to start because it could not find or load the Qt platform plugin "xcb".

Reinstalling the application may fix this problem.
Aborted (core dumped)
```
However, (lib)xcb is installed. This is on the Arch distro.

**Comment by setvisible** [comment]
Same error message on my side, on a Ubuntu VM.

There are missing dependencies in the AppImage build script I think.

**Comment by yochananmarqos** [comment]
@LukeZBaker Since you're using Arch, you might be interested in my AUR package: [`downzemall`](https://aur.archlinux.org/packages/downzemall/).

**Comment by LukeZBaker** [comment]
> @LukeZBaker Since you're using Arch, you might be interested in my AUR package: [`downzemall`](https://aur.archlinux.org/packages/downzemall/).

Thanks, I've installed it with your package. I wrote a review of DownZemAll! a few days ago, so I've referenced the AUR package.

**Comment by yochananmarqos** [comment]
@LukeZBaker Your article is how I came across it actually. 😉

**Comment by setvisible** [comment]
Duplicate of #78
